parameters:
#    christian_vermeulen_postalcode.example.class: ChristianVermeulen\PostalcodeBundle\Example

services:
   christian_vermeulen_postalcode:
       class: ChristianVermeulen\PostalcodeBundle\Wrapper\PostcodeNl_Api_RestClient
       arguments: [%christian_vermeulen_postalcode.key%, %christian_vermeulen_postalcode.secret%]
