parameters:
#    christian_vermeulen_postalcode.example.class: ChristianVermeulen\PostalcodeBundle\Example

services:
#    christian_vermeulen_postalcode.example:
#        class: %christian_vermeulen_postalcode.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
